/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Jabber Browser");
gchar *s = N_("Jabber ID:");
gchar *s = N_("jabber.org");
gchar *s = N_("*");
gchar *s = N_("Browse");
gchar *s = N_("Register");
gchar *s = N_("Search");
gchar *s = N_("Join");
gchar *s = N_("Browse");
gchar *s = N_("Register");
gchar *s = N_("Search");
gchar *s = N_("Join");
gchar *s = N_("Information");
