/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Properties of  '%s'");
gchar *s = N_("<b><big>Contact Properties</big></b>");
gchar *s = N_("<b>Nickname</b>");
gchar *s = N_("  ");
gchar *s = N_("*");
gchar *s = N_("Change");
gchar *s = N_("<b>Subscription</b>");
gchar *s = N_("<b>JabberID</b>");
gchar *s = N_("...");
gchar *s = N_("<b>none|both|from|to</b> - blah blah blah...");
gchar *s = N_("Contact");
gchar *s = N_("<b>Personal</b>");
gchar *s = N_("   ");
gchar *s = N_("Full Name");
gchar *s = N_("Nickname");
gchar *s = N_("Birthday");
gchar *s = N_("<b>Contact</b>");
gchar *s = N_("E-Mail");
gchar *s = N_("Phone");
gchar *s = N_("Homepage");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("General");
gchar *s = N_("Street");
gchar *s = N_("City");
gchar *s = N_("State");
gchar *s = N_("Postal Code");
gchar *s = N_("Country");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Location");
gchar *s = N_("Name");
gchar *s = N_("Unit");
gchar *s = N_("Position");
gchar *s = N_("Role");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Organization");
gchar *s = N_("About contact");
gchar *s = N_("   ");
gchar *s = N_("<b>Software</b>");
gchar *s = N_("Client Name");
gchar *s = N_("Client Version");
gchar *s = N_("Operating System");
gchar *s = N_("?");
gchar *s = N_("?");
gchar *s = N_("?");
gchar *s = N_("Computer");
