/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("%s");
gchar *s = N_("Click here for menu");
gchar *s = N_("label1");
gchar *s = N_("Add this contact...");
gchar *s = N_("Message...");
gchar *s = N_("History...");
gchar *s = N_("Contact Info...");
gchar *s = N_("Clear Buffer");
gchar *s = N_("Block user");
gchar *s = N_("Tabify");
gchar *s = N_("Windowify");
gchar *s = N_("Open in new window");
gchar *s = N_("Close tab");
gchar *s = N_("Tab position");
gchar *s = N_("Top");
gchar *s = N_("Bottom");
gchar *s = N_("Left");
gchar *s = N_("Right");
