/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Conference");
gchar *s = N_("_Menu");
gchar *s = N_("Topic:");
gchar *s = N_("*");
gchar *s = N_("Change topic");
gchar *s = N_("Update topic");
gchar *s = N_("Cancel");
gchar *s = N_("Configure room");
gchar *s = N_("Send");
gchar *s = N_("Message...");
gchar *s = N_("Chat...");
gchar *s = N_("Contact Info...");
gchar *s = N_("Kick");
gchar *s = N_("Ban");
gchar *s = N_("Grant");
gchar *s = N_("Voice");
gchar *s = N_("Membership");
gchar *s = N_("Moderator Privileges");
gchar *s = N_("Ownership");
gchar *s = N_("Administrative Privileges");
gchar *s = N_("Revoke");
gchar *s = N_("Voice");
gchar *s = N_("Membership");
gchar *s = N_("Moderator Privileges");
gchar *s = N_("Ownership");
gchar *s = N_("Administrative Privileges");
gchar *s = N_("Configure room");
gchar *s = N_("<i>Fetching data. Please wait...</i>");
gchar *s = N_("Find");
gchar *s = N_("Find:");
gchar *s = N_("*");
gchar *s = N_("Change _nick");
gchar *s = N_("URL Grabber");
