/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Join Conference");
gchar *s = N_("_Server");
gchar *s = N_("_Room");
gchar *s = N_("_Nickname");
gchar *s = N_("_Password");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("_Join conference");
