/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Register new account");
gchar *s = N_("<b><big>Register account</big></b>");
gchar *s = N_("_Server");
gchar *s = N_("_Password");
gchar *s = N_("_Username");
gchar *s = N_("Password (_retype)");
gchar *s = N_("_Add to my accounts");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("_Name");
gchar *s = N_("   ");
gchar *s = N_("Sa_ve password");
