/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Message Archive");
gchar *s = N_("<b>Subject:</b>");
gchar *s = N_("<b>From:</b>");
gchar *s = N_("<b>Date:</b>");
gchar *s = N_("label4");
gchar *s = N_("label5");
gchar *s = N_("label6");
