/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("New Message");
gchar *s = N_("Message Archive");
gchar *s = N_("Join Chatroom");
gchar *s = N_("Browse Agents");
gchar *s = N_("Seacrh For Users");
gchar *s = N_("Register In Service");
gchar *s = N_("Online");
gchar *s = N_("Chat With Me!");
gchar *s = N_("Away");
gchar *s = N_("eXtended Away");
gchar *s = N_("Busy");
gchar *s = N_("Invisible");
gchar *s = N_("Disconnected");
