/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("New Message");
gchar *s = N_("<b>To:</b>");
gchar *s = N_("<b>Subject:</b>");
gchar *s = N_("*");
gchar *s = N_("*");
