/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Privacy settings");
gchar *s = N_("Set Ac_tive");
gchar *s = N_("Set _Default");
gchar *s = N_("_Modify");
