/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Edit List");
gchar *s = N_("_List Name");
gchar *s = N_("*");
gchar *s = N_("<b>Rule Type</b>");
gchar *s = N_("   ");
gchar *s = N_("_Jabber ID");
gchar *s = N_("*");
gchar *s = N_("_Group");
gchar *s = N_("*");
gchar *s = N_("_Subscription");
gchar *s = N_("both");
gchar *s = N_("to");
gchar *s = N_("from");
gchar *s = N_("none");
gchar *s = N_("<b>Action</b>");
gchar *s = N_("Allow");
gchar *s = N_("Deny");
gchar *s = N_("_Messages");
gchar *s = N_("_Incoming Presence");
gchar *s = N_("Outcoming _Presence");
gchar *s = N_("I_Q");
gchar *s = N_("_None of above (fall-back rule)");
gchar *s = N_("Apply this rule only to those packet types:");
