/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Register");
gchar *s = N_("Enter JabberID of an agent you want to register in:");
gchar *s = N_("users.jabber.org");
gchar *s = N_("*");
gchar *s = N_("label1");
gchar *s = N_("<b>Note</b>\n"
              "You have already been registered in this agent!");
gchar *s = N_("label2");
