/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Search for users");
gchar *s = N_("Which directory you want to search in?");
gchar *s = N_("*");
gchar *s = N_("users.jabber.org");
gchar *s = N_("label2");
gchar *s = N_("<i>Fetching form. Please wait...</i>");
gchar *s = N_("label9");
gchar *s = N_("label3");
gchar *s = N_("<i>Waiting for results...</i>");
gchar *s = N_("label10");
gchar *s = N_("<b>Search results</b>");
gchar *s = N_("Information on user");
gchar *s = N_("Add contact");
gchar *s = N_("label4");
