/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Question");
gchar *s = N_("User <b>%s</b> would like to add you to his/her roster. Do you agree?");
gchar *s = N_("Add to contact list");
